---
kind: pkgfile.Build
spec:
  targets:
    - toolchain
  reproducibleTargetName: toolchain
---
kind: common.Renovate
spec:
  customManagers:
    - customType: regex
      fileMatch:
        - Pkgfile
      matchStrings:
        - '# renovate: datasource=(?<datasource>.*?)(?:\s+extractVersion=(?<extractVersion>.+?))?(?:\s+versioning=(?<versioning>.+?))?\s+depName=(?<depName>.+?)?\s(?:\s+.*_(?:version|VERSION):\s+(?<currentValue>.*))?(?:\s.*_(?:ref|REF):\s+(?<currentDigest>.*))?'
      versioningTemplate: "{{#if versioning}}{{versioning}}{{else}}semver{{/if}}"
    - customType: regex
      fileMatch:
        - Pkgfile
        - Makefile
      matchStrings:
        - ghcr.io\/siderolabs\/bldr:(?<currentValue>v.*)
      depNameTemplate: siderolabs/bldr
      datasourceTemplate: github-tags
      versioningTemplate: semver
  packageRules:
    - matchPackageNames:
        - git://sourceware.org/git/binutils-gdb.git
      versioning: 'regex:^(?<major>\d+)_(?<minor>\d+)_?(?<patch>\d+)?$'
    - matchPackageNames:
        - git://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git
      allowedVersions: "<= 6.12"
